### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Jipsukka**
## What type of Pull Request is this?

Check all the applicable.

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Other 

## Description

Update dependencies. According dependabot, there were security issues in some versions.

## Tests

- [x] Not needed
- [ ] Unit tests added
- [ ] Integration tests added
- [ ] Visual verification done

## Code of Conduct

- [x] I have read and agreed to the [community code of conduct][coc]. The sole intention of this pull request is to improve the project codebase.

[coc]: https://github.com/paytrail/.github/blob/master/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by Matsuuu** [comment]
LGTM. These dependencies are in either the examples, or in the development dependencies, so no real security flaw is exposed to the component itself but it's good to update them either way

**Comment by Jipsukka** [comment]
> LGTM. These dependencies are in either the examples, or in the development dependencies, so no real security flaw is exposed to the component itself but it's good to update them either way

Still, good practice to update them to suppress warnings. No new versions are required though, but it's nice to have dev master up to date. Specially when dependabot won't update all dependencies.

**Comment by Matsuuu** [comment]
Yeah for sure.

I've been thinking of writing documentation on the paytrail docs about using the web component. Would the right place for it be [here](https://github.com/paytrail/documentation)

**Comment by Jipsukka** [comment]
> Yeah for sure.
> 
> I've been thinking of writing documentation on the paytrail docs about using the web component. Would the right place for it be [here](https://github.com/paytrail/documentation)?

In documentation under `payments/e2-interface` under `Supported libraries` would be correct place to add mention and links to library. Documentation how to use it besides installing should be inside repository itself.

**Pull request merged**
